# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Package

on:
  release:
    types: [released]

jobs:
  kc-version-matrix:
    name: Get last 10 Keycloak versions
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
      fail-fast: false
    steps:
      - id: set-matrix
        run: |
          VERSIONS=$( curl -L -s https://api.github.com/repos/keycloak/keycloak/releases | jq -c 'sort_by(.name)[-11:-1] | [ .[] | .version=.name | {version}]' )
          echo "matrix={\"include\":$VERSIONS}" >> $GITHUB_OUTPUT

  build:
    needs: kc-version-matrix
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{fromJson(needs.kc-version-matrix.outputs.matrix)}}
    steps:
      - uses: actions/checkout@v3
      - name: Set up Maven Central Repository
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
          server-id: central
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
          gpg-private-key: ${{ secrets.GPG_SIGNING_KEY }}
          gpg-passphrase: MAVEN_GPG_PASSPHRASE
      - name: Set version corresponding to Keycloak version
        run: mvn versions:set -DnewVersion=$(git describe --tags)-KC${{ matrix.version }}
      - name: Build and publish to maven central
        run: mvn -Dkeycloak.version=${{ matrix.version }} -B deploy --file pom.xml -P release --batch-mode 
        env:
          MAVEN_USERNAME: ${{ secrets.CENTRAL_TOKEN_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.CENTRAL_TOKEN_PASSWORD }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.GPG_SIGNING_KEY_PASSWORD }}
          MAVEN_GPG_KEY: ${{ secrets.GPG_SIGNING_KEY }}
      - name: Attach artifact to release
        uses: softprops/action-gh-release@v1
        with:
          files: target/keycloak-2fa-email-authenticator*
          name: Keycloak 2FA Email Authenticator v${{ github.event.release.tag_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

